### ISSUE TITLE
Please decide for one adapter type: logic or utility (or something else)

### ISSUE THREAD

**Issue by GermanBluefox** [o0shojo0o/ioBroker.seq#10]
The types in repository 
https://github.com/o0shojo0o/ioBroker.seq/blob/master/io-package.json#L123
and on github 
https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist.json#L1258
are different. 
Please sync them.

**Comment by o0shojo0o** [comment]
Thanks for the hint, is now fixed :)
