### ISSUE TITLE
Please ensure proper URL formatting at wrong user input with "/" at end of URL

### ISSUE THREAD

**Issue by DutchmanNL** [o0shojo0o/ioBroker.seq#70]
When I typ an URL or copy paste and forget to remove the / behind the URL SEQ is not connecting.
This is a result of incorrect used URL http://domain.com/:port

Can you please ensue if a / is present at the end it will be ignored and the port not set behind an ?

Thank you

**Comment by o0shojo0o** [comment]
Fixed in version: 0.2.3
