### ISSUE TITLE
Please add normal description of adapter in io-package.json

### ISSUE THREAD

**Issue by GermanBluefox** [o0shojo0o/ioBroker.seq#74]
Please add normal description of adapter here:
https://github.com/o0shojo0o/ioBroker.seq/blob/master/io-package.json#L176

Else the user sees only that:
![image](https://user-images.githubusercontent.com/4582016/105232578-e0bad880-5b68-11eb-9d6a-35ffcb423dbf.png)

**Comment by o0shojo0o** [comment]
Fixed in release: 0.2.5
